stages:
  - docker-image-build
  - docker-run-container


be-image:
  stage: docker-image-build
  script:
    - cd streetSoccerManager-Backend/streetSoccerManager/
    - ./gradlew build
    - ./gradlew.bat --stop
    - docker build --build-arg JAR_FILE=build/libs/*.jar -t scm-be .

fe-image:
  stage: docker-image-build
  script:
    - cd streetSoccerManager-Frontend/street-soccer-manager/
    - docker build -t scm-fe .

run-db-container:
  stage: docker-run-container
  script:
    - docker run -d -p 1521:1521 -p 81:81 -v /c/TESTDB:/data --name=h2db joedoe/h2db
