stages:
  - build
  - test

build:
  stage: build
  script:
    - cd streetSoccerManager-Backend/streetSoccerManager/
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd streetSoccerManager-Backend/streetSoccerManager/
    - ./gradlew test
    - ./gradlew.bat --stop