stages:
  - build
  - test
  - sonarqube-analys
  - be-docker

build:
  stage: build
  script:
    - cd streetSoccerManager-Backend/streetSoccerManager/
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd streetSoccerManager-Backend/streetSoccerManager/
    - ./gradlew test
    - ./gradlew.bat --stop

sonarqube-analys:
  stage: sonarqube-analys
  script: 
    - cd streetSoccerManager-Backend/streetSoccerManager/
    - ./gradlew sonarqube
    - ./gradlew.bat --stop

be-docker:
  stage: be-docker
  script:
    - cd streetSoccerManager-Backend/streetSoccerManager/
    - ./gradlew build
    - ./gradlew.bat --stop
    - docker build --build-arg JAR_FILE=build/libs/*.jar -t test-be .