stages:
  - docker-image-build

be-image:
  stage: docker-image-build
  script:
    - cd streetSoccerManager-Backend/streetSoccerManager/
    - ./gradlew build
    - ./gradlew.bat --stop
    - docker build --build-arg JAR_FILE=build/libs/*.jar -t scm-be .

fe-image:
  stage: docker-image-build
  script:
    - cd streetSoccerManager-Frontend/street-soccer-manager/
    - docker build -t scm-fe .