stages:
  - build
  - test

build:
  stage: build
  script:
    - cd streetSoccerManager/streetSoccerManager/
    - ./gradlew build -x test

test:
  stage: test
  script:
    - cd streetSoccerManager/streetSoccerManager/
    - ./gradlew test